apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: hospital_management_system-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
