services:
  backend:
    build:
      context: ../backend
      dockerfile: ../ops/docker/Dockerfile.backend
    env_file: ../.env
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  worker:
    build:
      context: ../backend
      dockerfile: ../ops/docker/Dockerfile.worker
    env_file: ../.env
    environment:
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - SIMULATED_JOB_DELAY_MS=2000
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
      dockerfile: ../ops/docker/Dockerfile.frontend
    ports:
      - "5173:5173"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
